development: &default
  adapter: postgresql
  encoding: unicode
  database: dev_development
  pool: 5
  username: igorsheiko
  password: 1111
test:
  <<: *default
  database: dev_test
production:
  <<: *default
  database: dev_production