development: &default
  adapter: postgresql
  encoding: unicode
  database: dev_development
  pool: 5
  username: postgres
  password:
  host: db
test:
  <<: *default
  database: dev_test
production:
  <<: *default
  database: dev_production