# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4813d9bb2ec0438ed971bd3782cc34c024fd1c7a2a11c9e46ee615493e7cc480c36b8d42b0e14d32ad36b9fe01b69e7ffeabb34a0ababa411c14e6d3da93e7a2

test:
  secret_key_base: c70e8141e9d217b27bbea663147618695cf8fa958c358699804628033d952b3b94603e0e8a3597ce5d65d21d72d81c3092d4207cf678a423e9d8da3457ff0c3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
